#ODMD GENERATED WORKFLOW, don't change unless you are sure

name: ODMD_OdmdBuildUserAuth-CdkGithubWFus-east-1-workspace0
on:
  workflow_dispatch:
    inputs:
      aws_credentials:
        type: string
        required: false
        default: ''
        description: | 
          Your AWS credentials in the format:
          [workspace0_Role/Profile]
          aws_access_key_id=01234_id
          aws_secret_access_key=56689_secret
          aws_session_token=token0123456789
      message:
        type: string
        required: false
        default: ''
        description: 'additional message'
      ghWflPpStackName:
        type: string
        required: false
        default: ''
        description: 'the stack to reload, ignored by default'
jobs:
  odmd_job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - uses: ondemandenv/wflact-resolvEnvars@main
        with:
          aws_credentials: ${{github.event.inputs.aws_credentials}}
          trigger_message: ${{github.event.inputs.message}}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: OdmdBuildUserAuth
          ODMD_awsRegion: us-east-1
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_OdmdBuildUserAuth_CdkGithubWFus_east_1_workspace0'] }}
      
      - name: run enver local script
        run: |
          set -ex
    
          if [[ -n "${{ env.ODMD_work_dir }}" ]]; then
            cd "${{ env.ODMD_work_dir }}"
            echo "Changed directory to ${{ env.ODMD_work_dir }}"
          else
            echo "ODMD_work_dir is empty, staying in current directory"
          fi
          
          env | grep -i ^ODMD
          pwd
          
          if [ -f ${{ env.ODMD_buildScript }} ]; then
            chmod +x ${{ env.ODMD_buildScript }}
            ./${{ env.ODMD_buildScript }}
          else
            echo "${{ env.ODMD_buildScript }} does not exist, continue ..."
          fi
          
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: OdmdBuildUserAuth
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_OdmdBuildUserAuth_CdkGithubWFus_east_1_workspace0'] }}      
          
      - uses: ondemandenv/wflact-buildProduces@main
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: OdmdBuildUserAuth
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_OdmdBuildUserAuth_CdkGithubWFus_east_1_workspace0'] }}

#